version: '3.8'

services:
  backend:
    image: node:18-alpine
    container_name: backend
    working_dir: /app
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=boardgames
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "8000:8000"
    command: sh -c "npm install && npm start"
    depends_on:
      - db

  frontend:
    image: node:18-alpine
    container_name: frontend
    working_dir: /app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm start"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: boardgames
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_INITDB_SKIP_TZINFO: "true"
      MYSQL_DEFAULT_AUTHENTICATION_PLUGIN: mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local